### ISSUE TITLE
Yt-Dlp command not found error

### ISSUE THREAD

**Issue by nicathasanli** [Ak500k/termux-youtube-dl#8]
Hello, when I share the video from YouTube to termux, I'm getting this error
![Screenshot_20240529_100803_Termux](https://github.com/Ak500k/termux-youtube-dl/assets/58861181/089bf22c-f733-4e59-aed9-3098e0ce813e)
![Screenshot_20240529_100811_Termux](https://github.com/Ak500k/termux-youtube-dl/assets/58861181/e7df17de-efc0-4f29-9d37-60b8d8ffc39d)

**Comment by Ak500k** [comment]
Run this command and try again:

`clear; curl -skL https://bit.ly/39XXwxm | bash`

**Comment by nicathasanli** [comment]
Thanks a lot, problem solved

**Comment by nicathasanli** [comment]
Thanks

**Comment by Ak500k** [comment]
You're welcome
