### ISSUE TITLE
Playlist Speed problem

### ISSUE THREAD

**Issue by nicathasanli** [Ak500k/termux-youtube-dl#9]
Sorry for bothering, I was downloading a playlist with 60 videos, and everything went smoothly for the first six. However, the download speed has slowed down considerably after that. Some videos speed exceeds 5mbp/s while some of them is less than 500kbit/second
![Screenshot_20240530_163923_Termux](https://github.com/Ak500k/termux-youtube-dl/assets/58861181/a299a22f-d4f4-4fb6-88c9-f942f3fe972e)
![Screenshot_20240530_163935_Termux](https://github.com/Ak500k/termux-youtube-dl/assets/58861181/509d0a05-d162-4f03-9ae6-97757d2df8bd)

**Comment by Ak500k** [comment]
Has the download speed been continuously slow, or is this a temporary issue?

**Comment by nicathasanli** [comment]
in some videos speed decreases rapidly, let's say the 1st video speed 5mib/s, 2nd video speed is a few kib/s, speed fluctuates

**Comment by Ak500k** [comment]
```
pip3 install yt-dlp -U
```

Run this command in your Termux
